//! Does materializing the residual stream beat re-summing it? A hand-written
//! PROBE — MSL generated by hand, no derivation — pricing todo.md item 7a
//! before any partitioner or cost-model work is built on the answer.
//!
//! sanic never materializes the residual stream: layer N's norm re-sums every
//! prior layer's contribution in-register. That deletes MLX's whole `Add×32`
//! class, but it makes each norm's arity grow with depth — measured in a real
//! step, the reduce climbs 6 µs at layer 0 to 31 µs at layer 15 while the k/v
//! folds beside it stay flat at ~17 µs, and the norms cost 0.951 ms where
//! arity 1 would cost 0.363.
//!
//! The two shapes, at llama-3.2-1B's geometry (16 layers, 2 norms each plus a
//! final one, hidden 2048):
//!
//! * RE-SUM (today): norm i reads `arity[i]` separate contribution buffers and
//!   sums them, in both the reduce and the apply. 545 buffer-reads per pass.
//! * MATERIALIZE: 32 adds fold each layer's output into one running residual
//!   buffer; every norm then reads ONE buffer. 130 buffer-reads total, plus 32
//!   extra dispatches.
//!
//! Same arithmetic, same answer, different amount of loading — which is the
//! whole question.

#![cfg(target_os = "macos")]

use sanic::metal::{Dispatch, MetalDevice};

const HIDDEN: usize = 2048;
const LAYERS: usize = 16;

/// Arity of each norm, in emission order: two norms per layer whose depth
/// grows by one contribution per layer, then the final norm. This is the
/// shape the dump shows (`Add` counts 1, 3, 5, …, 65).
fn arities() -> Vec<usize> {
    let mut a: Vec<usize> = Vec::new();
    for layer in 0..LAYERS {
        a.push(2 * layer + 1);
        a.push(2 * layer + 1);
    }
    a.push(2 * LAYERS + 1);
    a
}

/// One reduce and one apply kernel per distinct arity. Each reads `k` slices
/// of one contributions buffer — same loads and same adds as reading `k`
/// separate buffers, without needing `k` bind slots.
fn msl(arities: &[usize]) -> String {
    let mut src = String::from(
        r#"
#include <metal_stdlib>
using namespace metal;
inline float bf(ushort v) { return as_type<float>((uint)v << 16u); }
inline ushort to_bf(float f) {
    uint b = as_type<uint>(f);
    return (ushort)((b + 0x7fffu + ((b >> 16) & 1u)) >> 16);
}
"#,
    );
    let mut seen: Vec<usize> = arities.to_vec();
    seen.sort_unstable();
    seen.dedup();
    for k in seen {
        // reduce: sum k contributions per element, then Σx² over hidden
        src.push_str(&format!(
            r#"
// one threadgroup of 128 threads, the geometry the emitted norm reduce runs
// at (SANIC_DEBUG=4 reports grid=(1,1,1) block=(128,1,1))
[[max_total_threads_per_threadgroup(128)]]
kernel void reduce_k{k}(
    device const ushort* contributions [[buffer(0)]],
    device float* denom [[buffer(1)]],
    uint tid [[thread_position_in_threadgroup]],
    uint lane [[thread_index_in_simdgroup]],
    uint sgid [[simdgroup_index_in_threadgroup]]
) {{
    threadgroup float partial[4];
    float acc = 0.0f;
    for (uint h = tid; h < {HIDDEN}u; h += 128u) {{
        float x = 0.0f;
        for (uint j = 0; j < {k}u; j++) x += bf(contributions[j * {HIDDEN}u + h]);
        acc += x * x;
    }}
    acc = simd_sum(acc);
    if (lane == 0) partial[sgid] = acc;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (tid == 0) {{
        float s = partial[0] + partial[1] + partial[2] + partial[3];
        denom[0] = rsqrt(s / {HIDDEN}.0f + 1e-5f);
    }}
}}

[[max_total_threads_per_threadgroup(1024)]]
kernel void apply_k{k}(
    device const ushort* contributions [[buffer(0)]],
    device const ushort* weight [[buffer(1)]],
    device const float* denom [[buffer(2)]],
    device ushort* outb [[buffer(3)]],
    uint gid [[thread_position_in_grid]]
) {{
    if (gid >= {HIDDEN}u) return;
    float x = 0.0f;
    for (uint j = 0; j < {k}u; j++) x += bf(contributions[j * {HIDDEN}u + gid]);
    outb[gid] = to_bf(x * denom[0] * bf(weight[gid]));
}}
"#
        ));
    }
    // the add that materializing needs: running residual += contribution
    src.push_str(&format!(
        r#"
[[max_total_threads_per_threadgroup(1024)]]
kernel void residual_add(
    device const ushort* running [[buffer(0)]],
    device const ushort* contribution [[buffer(1)]],
    device ushort* outb [[buffer(2)]],
    uint gid [[thread_position_in_grid]]
) {{
    if (gid >= {HIDDEN}u) return;
    outb[gid] = to_bf(bf(running[gid]) + bf(contribution[gid]));
}}
"#
    ));
    src
}

fn bf16(value: f64) -> u16 {
    let bits = (value as f32).to_bits();
    ((bits + 0x7fff + ((bits >> 16) & 1)) >> 16) as u16
}

fn bytemuck_cast(values: &[u16]) -> &[u8] {
    // SAFETY: u16 has no padding and any bit pattern is a valid u8 pair
    unsafe { std::slice::from_raw_parts(values.as_ptr() as *const u8, std::mem::size_of_val(values)) }
}

#[test]
fn materializing_the_residual_against_re_summing_it() {
    let Some(device) = MetalDevice::open() else {
        println!("SKIP: no Metal device");
        return;
    };
    let arities = arities();
    let deepest = *arities.iter().max().unwrap();
    let pipes = device.compile(&msl(&arities));

    // `deepest` contributions of HIDDEN elements each, laid out back to back
    let contributions: Vec<u16> = (0..deepest * HIDDEN)
        .map(|i| bf16(((i % 17) as f64 - 8.0) / 512.0))
        .collect();
    let contribution_buffer = device.from_bytes(bytemuck_cast(&contributions));
    let norm_weight: Vec<u16> = (0..HIDDEN).map(|i| bf16(1.0 + (i % 5) as f64 / 64.0)).collect();
    let weight = device.from_bytes(bytemuck_cast(&norm_weight));

    // ── shape A: re-sum, what sanic emits today ──────────────────────────────
    let mut re_sum: Vec<Dispatch> = Vec::new();
    let mut outs_a = Vec::new();
    for &k in &arities {
        let denom = device.alloc_f32(1);
        let out = device.alloc_elems(HIDDEN, sanic::ir::Dtype::BF16);
        re_sum.push(Dispatch {
            pipe: pipes.get(&format!("reduce_k{k}")),
            inputs: vec![contribution_buffer.clone()],
            output: denom.clone(),
            grid: 128,
            argbuf: None,
        });
        re_sum.push(Dispatch {
            pipe: pipes.get(&format!("apply_k{k}")),
            inputs: vec![contribution_buffer.clone(), weight.clone(), denom.clone()],
            output: out.clone(),
            grid: HIDDEN,
            argbuf: None,
        });
        outs_a.push(out);
    }

    // ── shape B: materialize once per layer, every norm at arity 1 ───────────
    // The running residual is rebuilt by `deepest - 1` adds; each norm then
    // reads the running buffer that carries its own arity's worth of terms.
    let mut materialize: Vec<Dispatch> = Vec::new();
    let mut running: Vec<sanic::metal::MetalBuf> = vec![contribution_buffer.clone()];
    for step in 1..deepest {
        let next = device.alloc_elems(HIDDEN, sanic::ir::Dtype::BF16);
        materialize.push(Dispatch {
            pipe: pipes.get("residual_add"),
            inputs: vec![running[step - 1].clone(), contribution_buffer.slice(step * HIDDEN * 2)],
            output: next.clone(),
            grid: HIDDEN,
            argbuf: None,
        });
        running.push(next);
    }
    let mut outs_b = Vec::new();
    for &k in &arities {
        let denom = device.alloc_f32(1);
        let out = device.alloc_elems(HIDDEN, sanic::ir::Dtype::BF16);
        materialize.push(Dispatch {
            pipe: pipes.get("reduce_k1"),
            inputs: vec![running[k - 1].clone()],
            output: denom.clone(),
            grid: 128,
            argbuf: None,
        });
        materialize.push(Dispatch {
            pipe: pipes.get("apply_k1"),
            inputs: vec![running[k - 1].clone(), weight.clone(), denom.clone()],
            output: out.clone(),
            grid: HIDDEN,
            argbuf: None,
        });
        outs_b.push(out);
    }

    // same answer first, then the timing means something
    device.run(&re_sum);
    device.run(&materialize);
    let worst = outs_a
        .iter()
        .zip(&outs_b)
        .map(|(a, b)| {
            let (x, y) = (device.read_f32(a, HIDDEN / 2), device.read_f32(b, HIDDEN / 2));
            x.iter()
                .zip(&y)
                .map(|(l, r)| (*l as f64 - *r as f64).abs() / (1.0 + l.abs() as f64))
                .fold(0.0, f64::max)
        })
        .fold(0.0, f64::max);
    assert!(worst < 5e-2, "the two shapes disagree: {worst:e}");

    let time = |dispatches: &[Dispatch]| -> f64 {
        let graph = device.capture(dispatches);
        (0..30)
            .filter_map(|_| device.run_graph_timed(&graph).ok())
            .fold(f64::INFINITY, f64::min)
    };
    let (mut a, mut b) = (f64::INFINITY, f64::INFINITY);
    for _ in 0..3 {
        a = a.min(time(&re_sum));
        b = b.min(time(&materialize));
    }
    println!(
        "  re-sum (today)   {:3} dispatches  {:7.1}us\n  materialize      {:3} dispatches  {:7.1}us   {:.2}x",
        re_sum.len(),
        a * 1e6,
        materialize.len(),
        b * 1e6,
        a / b,
    );
    // The finding, pinned: materializing WINS. The probe's absolute numbers
    // run ~1.6x hot against a real step (its norms have no big matmuls beside
    // them to hide behind), so read the ratio, not the microseconds.
    assert!(
        b < a,
        "re-summing now WINS ({:.1}us vs {:.1}us) — revisit todo.md item 7a",
        a * 1e6,
        b * 1e6,
    );
}
