//! GPT-2 byte-level BPE — the ENCODER (prompts were pre-tokenized ids until
//! now; the decoder has always lived in the examples' stream printers).
//!
//! Dependency-free, like the safetensors reader: the vocabulary comes
//! through the same tiny JSON parser, the merges from `merges.txt`, and the
//! GPT-2 pre-tokenizer regex
//! `'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+`
//! is hand-rolled as the ordered-alternative matcher it is (letters, digits,
//! punctuation runs with one optional leading space; a whitespace run keeps
//! its last space for the following word). Exactness is the point — a wrong
//! split silently changes ids — so `tests/bpe.rs` holds tokenizations
//! generated by the HuggingFace tokenizer on this repo's own vocab files.
//!
//! Trinity's tokenizer is NOT implemented, deliberately: its pre-tokenizer
//! is a sequence of lookahead regexes (digit grouping by threes, `\G`
//! anchors) that this crate cannot honestly reproduce without a regex
//! engine, and an approximation would corrupt prompts silently. Trinity
//! prompts stay pre-tokenized ids — a decline, stated, not a gap.

use std::collections::HashMap;

use crate::safetensors::{Json, parse_json};

/// The GPT-2 byte↔unicode bijection: printable latin-1 bytes map to
/// themselves, the rest to 256+n — every byte becomes one visible char, so
/// BPE runs over strings without losing binary fidelity.
fn byte_to_unicode() -> [char; 256] {
    let mut table = ['\0'; 256];
    let mut used = [false; 256];
    for b in 0x21..=0x7e_usize {
        table[b] = b as u8 as char;
        used[b] = true;
    }
    for b in 0xa1..=0xac_usize {
        table[b] = char::from_u32(b as u32).unwrap();
        used[b] = true;
    }
    for b in 0xae..=0xff_usize {
        table[b] = char::from_u32(b as u32).unwrap();
        used[b] = true;
    }
    let mut n = 0u32;
    for b in 0..256 {
        if !used[b] {
            table[b] = char::from_u32(256 + n).unwrap();
            n += 1;
        }
    }
    table
}

pub struct Bpe {
    /// token string (in byte↔unicode space) → id
    encoder: HashMap<String, u32>,
    /// merge pair → rank (lower merges first)
    ranks: HashMap<(String, String), usize>,
    byte_map: [char; 256],
}

impl Bpe {
    /// Load from GPT-2's `vocab.json` + `merges.txt`.
    pub fn from_gpt2(vocab_path: &str, merges_path: &str) -> Result<Bpe, String> {
        let vsrc = std::fs::read_to_string(vocab_path).map_err(|e| e.to_string())?;
        let Json::Obj(kvs) = parse_json(&vsrc)? else {
            return Err("vocab.json is not an object".into());
        };
        let mut encoder = HashMap::with_capacity(kvs.len());
        for (k, v) in kvs {
            let id = v.as_num().ok_or("vocab value is not a number")? as u32;
            encoder.insert(k, id);
        }
        let msrc = std::fs::read_to_string(merges_path).map_err(|e| e.to_string())?;
        let mut ranks = HashMap::new();
        for (rank, line) in msrc
            .lines()
            .filter(|l| !l.starts_with("#version") && !l.is_empty())
            .enumerate()
        {
            let (a, b) = line
                .split_once(' ')
                .ok_or_else(|| format!("bad merge line: {line}"))?;
            ranks.insert((a.to_string(), b.to_string()), rank);
        }
        Ok(Bpe {
            encoder,
            ranks,
            byte_map: byte_to_unicode(),
        })
    }

    /// Encode text to token ids. Exact GPT-2 semantics; every byte of every
    /// pre-token is representable (the byte-level property), so this never
    /// fails on valid UTF-8 input.
    pub fn encode(&self, text: &str) -> Vec<u32> {
        let mut out = Vec::new();
        for piece in pretokenize(text) {
            // bytes → visible chars, then merge by rank
            let symbols: Vec<String> = piece
                .as_bytes()
                .iter()
                .map(|&b| self.byte_map[b as usize].to_string())
                .collect();
            for sym in self.merge(symbols) {
                match self.encoder.get(&sym) {
                    Some(&id) => out.push(id),
                    None => panic!("BPE produced a symbol outside the vocab: {sym:?}"),
                }
            }
        }
        out
    }

    fn merge(&self, mut syms: Vec<String>) -> Vec<String> {
        while syms.len() > 1 {
            // the lowest-ranked adjacent pair, if any
            let mut best: Option<(usize, usize)> = None; // (rank, index)
            for i in 0..syms.len() - 1 {
                if let Some(&r) = self
                    .ranks
                    .get(&(syms[i].clone(), syms[i + 1].clone()))
                    && best.is_none_or(|(br, _)| r < br)
                {
                    best = Some((r, i));
                }
            }
            let Some((_, mut i)) = best else { break };
            // merge every occurrence of that pair, left to right
            let (a, b) = (syms[i].clone(), syms[i + 1].clone());
            while i < syms.len() - 1 {
                if syms[i] == a && syms[i + 1] == b {
                    let joined = format!("{}{}", syms[i], syms[i + 1]);
                    syms[i] = joined;
                    syms.remove(i + 1);
                }
                i += 1;
                // advance to the next occurrence
                while i < syms.len() - 1 && !(syms[i] == a && syms[i + 1] == b) {
                    i += 1;
                }
            }
        }
        syms
    }
}

/// The GPT-2 pre-tokenizer, as the ordered-alternative matcher its regex
/// denotes. Split points decide merge boundaries, so this must be EXACT —
/// held to HuggingFace outputs in `tests/bpe.rs`.
fn pretokenize(text: &str) -> Vec<String> {
    let chars: Vec<char> = text.chars().collect();
    let n = chars.len();
    let is_other = |c: char| !c.is_whitespace() && !c.is_alphabetic() && !c.is_numeric();
    let mut out = Vec::new();
    let mut i = 0usize;
    while i < n {
        let c = chars[i];
        // 's | 't | 're | 've | 'm | 'll | 'd  (lowercase only, as in GPT-2)
        if c == '\'' && i + 1 < n {
            let two: String = chars[i..(i + 2).min(n)].iter().collect();
            let three: String = chars[i..(i + 3).min(n)].iter().collect();
            if three == "'re" || three == "'ve" || three == "'ll" {
                out.push(three);
                i += 3;
                continue;
            }
            if matches!(two.as_str(), "'s" | "'t" | "'m" | "'d") {
                out.push(two);
                i += 2;
                continue;
            }
        }
        // ` ?\p{L}+` / ` ?\p{N}+` / ` ?[^\s\p{L}\p{N}]+`
        let lead_space = c == ' ' && i + 1 < n;
        let start = if lead_space { i + 1 } else { i };
        if start < n {
            let class: Option<fn(char) -> bool> = if chars[start].is_alphabetic() {
                Some(|c: char| c.is_alphabetic())
            } else if chars[start].is_numeric() {
                Some(|c: char| c.is_numeric())
            } else if is_other(chars[start]) {
                Some(is_other)
            } else {
                None
            };
            if let Some(f) = class {
                let mut j = start + 1;
                while j < n && f(chars[j]) {
                    j += 1;
                }
                out.push(chars[i..j].iter().collect());
                i = j;
                continue;
            }
        }
        // whitespace: `\s+(?!\S)` then `\s+` — a run followed by a word
        // keeps its LAST char for that word's optional leading space
        debug_assert!(c.is_whitespace());
        let mut j = i + 1;
        while j < n && chars[j].is_whitespace() {
            j += 1;
        }
        let end = if j < n && j - i > 1 { j - 1 } else { j };
        out.push(chars[i..end].iter().collect());
        i = end;
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn byte_table_is_a_bijection() {
        let t = byte_to_unicode();
        let mut seen = std::collections::HashSet::new();
        for c in t {
            assert!(seen.insert(c));
        }
    }

    #[test]
    fn pretokenize_matches_the_regex_on_basics() {
        assert_eq!(
            pretokenize("Hello, I'm a language model,"),
            vec!["Hello", ",", " I", "'m", " a", " language", " model", ","]
        );
        // a whitespace run keeps its last space for the following word
        assert_eq!(pretokenize("  a"), vec![" ", " a"]);
        assert_eq!(pretokenize("a  "), vec!["a", "  "]);
        // a single non-space whitespace binds to nothing
        assert_eq!(pretokenize("\tand"), vec!["\t", "and"]);
    }
}
