//! §3.1 — Intermediate representation.
//!
//! The IR is generated by a *small basis*: `Input`, `Map`, `Reduce`, `Scan`,
//! `Gather`. `MatMul`, `Softmax`, `Attention`, the SSM scan, etc. are **derived**
//! as compositions of that basis (the constructors at the bottom of this file),
//! so Stage 1 and Stage 2A handle them with no special cases.
//!
//! Axes are named (`&'static str`). The analysis is per-(node, axis): the same
//! axis can be reduced in one sub-expression and free in another (§4.3), so we
//! never collapse structure onto the output.

use std::rc::Rc;

use crate::op::{BinOp, Monoid};

pub type Axis = &'static str;
pub type Node = Rc<NodeKind>;

/// An elementwise / broadcast map. We don't need its numeric semantics for the
/// analysis — only its name (for pattern recognition in Stage 2A) and whether it
/// **preserves linearity** in its arguments (§4.2: scaling/addition do, `exp`
/// and `gelu` do not).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MapFn {
    pub name: &'static str,
    pub preserves_linear: bool,
}

impl MapFn {
    pub const fn new(name: &'static str, preserves_linear: bool) -> Self {
        MapFn {
            name,
            preserves_linear,
        }
    }
}

#[derive(Debug)]
pub enum NodeKind {
    /// Raw data; no dependence on any axis → always FREE.
    Input { name: &'static str, axes: Vec<Axis> },
    /// Elementwise/broadcast; introduces no dependence on any axis.
    Map { f: MapFn, inputs: Vec<Node> },
    /// Folds `axis` with `op`; the write projects `axis` out.
    Reduce { src: Node, axis: Axis, op: BinOp },
    /// Prefix recurrence over `axis`; foldable iff `op` is associative.
    Scan { src: Node, axis: Axis, op: BinOp },
    /// `src[index[...]]`; access function is data-dependent → OPAQUE.
    Gather { src: Node, index: Node, axis: Axis },
}

// ── basis constructors ──────────────────────────────────────────────────────

pub fn input(name: &'static str, axes: &[Axis]) -> Node {
    Rc::new(NodeKind::Input {
        name,
        axes: axes.to_vec(),
    })
}

pub fn map(f: MapFn, inputs: Vec<Node>) -> Node {
    Rc::new(NodeKind::Map { f, inputs })
}

pub fn reduce(src: Node, axis: Axis, op: BinOp) -> Node {
    Rc::new(NodeKind::Reduce { src, axis, op })
}

pub fn scan(src: Node, axis: Axis, op: BinOp) -> Node {
    Rc::new(NodeKind::Scan { src, axis, op })
}

pub fn gather(src: Node, index: Node, axis: Axis) -> Node {
    Rc::new(NodeKind::Gather { src, index, axis })
}

// ── named map functions (used by the Stage 2A recognizer) ────────────────────

pub const MUL: MapFn = MapFn::new("mul", true);
pub const DIV: MapFn = MapFn::new("div", true);
pub const ADD_F: MapFn = MapFn::new("add", true);
pub const SUB_F: MapFn = MapFn::new("sub", true);
pub const ONE: MapFn = MapFn::new("one", false); // x ↦ 1, materializes a count
/// `exp(x − m)`: the softmax shift. Takes inputs `[x, m]`. Nonlinear.
pub const EXP_SUB: MapFn = MapFn::new("exp_sub", false);
pub const LOG: MapFn = MapFn::new("log", false);
pub const TANH: MapFn = MapFn::new("tanh", false);

// ── derived operators (compositions of the basis, §3.1) ──────────────────────

/// `MatMul(A, B; contract=k) ≜ Reduce( Map(×, A, B), k, ADD )`.
pub fn matmul(a: Node, b: Node, contract: Axis) -> Node {
    reduce(map(MUL, vec![a, b]), contract, BinOp::Monoid(Monoid::Add))
}

/// `Softmax(x; axis=k)` — the *normalized weights*, exactly as in §3.1:
/// ```text
/// m = Reduce(x, k, MAX); e = Map(exp∘sub, x, m); s = Reduce(e, k, ADD); Map(÷, e, s)
/// ```
pub fn softmax(x: Node, k: Axis) -> Node {
    let m = reduce(x.clone(), k, BinOp::Monoid(Monoid::Max));
    let e = map(EXP_SUB, vec![x, m]);
    let s = reduce(e.clone(), k, BinOp::Monoid(Monoid::Add));
    map(DIV, vec![e, s])
}

/// `Attention(Q,K,V) ≜ MatMul( Softmax(MatMul(Q,K;d), k), V; contract=k )`.
pub fn attention(q: Node, k_in: Node, v: Node, d: Axis, k: Axis) -> Node {
    let scores = matmul(q, k_in, d);
    let weights = softmax(scores, k);
    matmul(weights, v, k)
}

/// A linear / SSM recurrence `h_t = A_t·h_{t−1} + b_t` as a `Scan` over `t`
/// whose step is affine-map composition (associative → MONOIDAL, §5.4).
pub fn ssm_scan(params: Node, t: Axis) -> Node {
    scan(params, t, BinOp::AffineCompose)
}

/// A `tanh`-RNN `h_t = tanh(W·h_{t−1} + x_t)`: a `Scan` over `t` with a
/// non-associative step → SEQUENTIAL (§6).
pub fn tanh_rnn(x: Node, t: Axis) -> Node {
    scan(map(TANH, vec![x]), t, BinOp::NonAssoc("tanh_recur"))
}

/// Embedding lookup: a `Gather` along the vocabulary axis → OPAQUE (§6).
pub fn embedding(table: Node, ids: Node, axis: Axis) -> Node {
    gather(table, ids, axis)
}
